# Machine Learning - Regression

In [ ]:
import numpy as np
import pandas as pd

from sklearn import datasets

## Motivation

Ten baseline variables, age, sex, body mass index, average blood pressure, and six blood serum measurements were obtained for each of n = 442 diabetes patients, as well as the response of interest, a quantitative measure of disease progression one year after baseline.

Source: https://scikit-learn.org/stable/datasets/toy_dataset.html#diabetes-dataset

In [2]:
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True, as_frame=True)
diabetes = pd.concat([diabetes_X, diabetes_y], axis=1)
diabetes.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019907 -0.017646   151.0  
1 -0.039493 -0.068332 -0.092204    75.0  
2 -0.002592  0.002861 -0.025930   141.0  
3  0.034309  0.022688 -0.009362   206.0  
4 -0.002592 -0.031988 -0.046641   135.0

First 10 columns are numeric predictive values

Column 11 is a quantitative measure of disease progression one year after baseline


| Feature       | Description     |
| :------------- | :----------: |
| age | age in years|
| sex | sex |
| bmi | body mass index|
| bp | average blood pressure|
| s1 | tc, T-Cells (a type of white blood cells)|
| s2 | ldl, low-density lipoproteins|
| s3 | hdl, high-density lipoproteins|
| s4 | tch, thyroid stimulating hormone|
| s5 | ltg, lamotrigine|
| s6 | glu, blood sugar level|

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times the square root of n_samples (i.e. the sum of squares of each column totals 1).

## Linear Regression

The first approach is to work with a linear model. Let's suppose we have $n$ samples of data and each sample $x^{(i)} \in \mathbb{R}^{p \times 1}$  where $p$ denotes the number of features. Then

$$x^{(i)} = (x^{(i)}_1, ..., x^{(i)}_n)^\top \qquad, \forall i=1,\dots, \, n$$

And for each $x^{(i)}$ we know the target value denoted by $y^{(i)} \in \mathbb{R}$, $i=1,\dots, n$ .

Let's consider a lineal function $h$ and a vector of coefficients $\beta \in \mathbb{R}^{(p+1) \times 1}$ such that

$$\begin{align*}
f_\beta(x^{(i)}) &= \beta_0 + \beta_1 x^{(i)}_1 + \beta_2 x^{(i)}_2 + ... + \beta_p x^{(i)}_p \\
    &= \begin{bmatrix} 1 & x^{(i)}_1 & x^{(i)}_2 & \dots & x^{(i)}_p\end{bmatrix}
        \begin{bmatrix} \beta_0 \\ \beta_1 \\ \beta_2 \\ \vdots \\ \beta_p\end{bmatrix}  \\
    &= \left(x^{(i)}\right)^\top \beta \qquad \left(\text{where} \quad x^{(i)}_0 = 1\right)
\end{align*}  $$ 

Let's define the matrix of inputs $X \in \mathbb{R}^{n \times (p + 1)} $, also know as design matrix, model matrix or regressor matrix, and the output vector $Y \in \mathbb{R}^n$ such that 

$$
\begin{align*}
X = 
\begin{bmatrix} 
(x^{(1)})^\top  \\ 
(x^{(2)})^\top  \\
\vdots \\
(x^{(n)})^\top  \\
\end{bmatrix}
=
\begin{bmatrix} 
1 & x^{(1)}_1 & \dots & x^{(1)}_p \\ 
1 & x^{(2)}_1 & \dots & x^{(2)}_p \\
\vdots & \vdots & & \vdots \\
1 & x^{(n)}_1 & \dots & x^{(n)}_p \\
\end{bmatrix} 
\qquad
\text{and}
\qquad
Y = \begin{bmatrix}y^{(1)} \\ y^{(2)} \\ \vdots \\ y^{(n)}\end{bmatrix}
\end{align*}
$$




Notice that now we can write this as a matrix operation

$$
\begin{align*}
X \beta &= 
\begin{bmatrix}
1 & x_1^{(1)} & ... & x_p^{(1)} \\
\vdots & \vdots & & \vdots \\
1 & x_1^{(n)} & ... & x_p^{(n)} \\
\end{bmatrix}
\begin{bmatrix}\beta_0 \\ \beta_1 \\ \vdots \\ \beta_p \end{bmatrix} 
 = 
\begin{bmatrix}
\beta_0 + x^{(1)}_1 \beta_1 + ... + x^{(1)}_p \beta_p \\
\vdots \\
\beta_0 + x^{(n)}_1 \beta_1 + ... + x^{(n)}_p \beta_p \\
\end{bmatrix} 
 = 
\begin{bmatrix}
f_\beta(x^{(1)}) \\
\vdots \\
f_\beta(x^{(n)})
\end{bmatrix}
\end{align*}
$$


Then our goal is to find an adequate vector of coefficients $\beta$ such taht
$$
\begin{bmatrix}y^{(1)} \\ y^{(2)} \\ \vdots \\ y^{(n)}\end{bmatrix}
\approx
\begin{bmatrix}
f_\beta(x^{(1)}) \\
f_\beta(x^{(2)}) \\
\vdots \\
f_\beta(x^{(n)})
\end{bmatrix}
$$

that is equivalent to
$$Y \approx X \beta $$

### Naive Approach

$$
\hat{\beta} = (X^\top X)^{-1} X^\top Y
$$

In [3]:
y = diabetes_y.to_numpy().reshape(-1, 1)
X = diabetes_X.to_numpy()
# X = np.hstack((np.ones_like(y), X))

In [4]:
beta_naive = np.linalg.inv(X.T @ X) @ X.T @ y
beta_naive

array([[ -10.0098663 ],
       [-239.81564367],
       [ 519.84592005],
       [ 324.3846455 ],
       [-792.17563855],
       [ 476.73902101],
       [ 101.04326794],
       [ 177.06323767],
       [ 751.27369956],
       [  67.62669218]])

In [5]:
beta_ls, _, _, _ = np.linalg.lstsq(X, y)
beta_ls

array([[ -10.0098663 ],
       [-239.81564367],
       [ 519.84592005],
       [ 324.3846455 ],
       [-792.17563855],
       [ 476.73902101],
       [ 101.04326794],
       [ 177.06323767],
       [ 751.27369956],
       [  67.62669218]])

### Probabilistic Approach

Consider the following model

$$ Y = X \beta + \varepsilon $$

where $\varepsilon \sim  \mathcal{N}(0, \sigma^2 I)$.

Note that $\beta$ is not a random variable and then $Y \ | \ X \sim \mathcal{N}(X \beta, \sigma^2 I)$.


The likelihood function for such random variable is

$$
L(\theta) = \left( 2 \pi \sigma^2 \right)^{-n/2} \, \exp\left(- \frac{1}{2 \sigma ^2} || Y - X \theta ||^2 \right)
$$

Next, the log-likelihood (ignoring constants terms) is as follows
$$
l(\beta) = -\frac{n}{2} \log \sigma^2 - \frac{1}{2 \sigma ^2} || Y - X \beta ||^2
$$

To estimate $\beta$ we employ the Maximum Likelihood Estimation (MLE) method. Deriving $l(\beta)$ with respect to $\beta$ we obtain

$$
\frac{\partial l(\beta)}{\partial \beta}= - \frac{1}{\sigma ^2} \left( X^T Y + X^T X \beta \right)
$$

Equalling $\partial l(\beta) / \partial \beta = 0$ we show that

$$
\hat{\beta}_{MLE} = (X^T X)^{-1} X^T Y
$$.

Finally, we need to show it is a maximum (homework).

## Optimization

Let's define our cost function

$$J(\beta) = \frac{1}{2} \left\lVert Y - X \beta \right\rVert^2_2 =  \frac{1}{2} \sum_{i=1}^{n} \left( y^{(i)} - f_\beta(x^{(i)})\right)^2$$

The goal is to solve the following optimization problem

$$\min_{\beta} J(\beta) = \min_{\beta} \frac{1}{2}  \left\lVert Y - X \beta \right\rVert^2_2$$

Gradient descent is an optimization algorithm which is commonly-used to train machine learning models. The idea is to take repeated steps in the opposite direction of the gradient because this is the direction of steepest descent. 

The algorithm can be written as

$$\beta^{(n+1)} = \beta^{(n)} - \alpha \nabla_{\beta} J(\beta^{(n)})$$

where $\alpha >0$ is called learning rate. Now, let's compute the gradient of $J(\beta)$. For any $k = 0, \ldots, p$ we have

$$\begin{aligned}
\frac{\partial J(\beta)}{\partial \beta_k} &=
\frac{\partial }{\partial \beta_k} \frac{1}{2} \sum_{i=1}^{n} \left(  y^{(i)} - f_{\beta}(x^{(i)})\right)^2 \\
&= \frac{1}{2} \sum_{i=1}^{m}  2 \left(  y^{(i)} - f_{\beta}(x^{(i)}) \right) \frac{\partial f_{\beta}(x^{(i)})}{\partial \beta_k}\\
&= \sum_{i=1}^{n} \left(  y^{(i)} - f_{\beta}(x^{(i)})\right) x^{(i)}_k\end{aligned}$$

Then
$$
\begin{aligned}
    \nabla_{\beta} J(\beta)
    &= \left(
        \sum_{i=1}^{n} \left(  y^{(i)} - f_{\beta}(x^{(i)})\right) x^{(i)}_0,
        \dots,
        \sum_{i=1}^{n} \left(  y^{(i)} - f_{\beta}(x^{(i)})\right) x^{(i)}_p
    \right)^\top = X^\top \left( Y - X \beta \right)
\end{aligned}
$$

Note that $\alpha$ is a parameter from the algorithm and not from the model itself. These kind of parameters are usually named as __hyper-parameters__ and to find the best one is a big task itself.

In [6]:
max_iter = 10_000
lr = 1e-2
tol = 1e-6

n, m = X.shape  # Rows and columns
beta = np.random.rand(m, 1)
for i in range(1, max_iter + 1):
  # Restart gradient
  grad = np.zeros_like(beta, dtype=np.float64)
  for x_i, y_i in zip(X, y.flatten()):
    f_i = (x_i @ beta)  # Linear model evaluation
    # print(f_i)
    grad += (f_i - y_i) * x_i.reshape(-1, 1)
  beta_new = beta - lr * grad  # Update parameters
  # Stop criteria
  rel_error = np.linalg.norm(beta - beta_new) / (np.linalg.norm(beta) + 1e-12)
  if rel_error < tol:
    print(f"Converged! {rel_error:.2e} error in the {i}-th iteration")
    break
  else:
    beta = beta_new  # Update params for tolerance comparison

print(i)
beta

10000


array([[  -8.51919013],
       [-238.1434401 ],
       [ 523.61476308],
       [ 322.91326916],
       [-467.92000419],
       [ 219.43749726],
       [ -43.96758555],
       [ 135.69463421],
       [ 630.44900597],
       [  68.81894413]])

### Scikit-Learn

In [7]:
from sklearn.linear_model import LinearRegression

model = LinearRegression(fit_intercept=False)
model.fit(diabetes_X, diabetes_y)
print(f"Coefficients:\n {model.coef_.T}\n")


Coefficients:
 [ -10.0098663  -239.81564367  519.84592005  324.3846455  -792.17563855
  476.73902101  101.04326794  177.06323767  751.27369956   67.62669218]



## More Algorithms

### Ridge 

Ridge regression shrinks the regression coefficients by imposing a penalty on their size. The ridge coefficients minimize a penalized residual sum of squares,
$$
\min_\beta J(\beta) = \min_{\beta} \frac{1}{2}  \left\lVert y - X \beta \right\rVert^2_2 + \frac{\alpha}{2} \left\lVert \beta \right\rVert_2^2
$$
where $\alpha > 0$ is a complexity parameter that controls the amount of shrinkage. This penalization helps to deal with colinearity.

In [8]:
from sklearn.linear_model import Ridge

ridge_model = Ridge(alpha=0.5)
ridge_model.fit(diabetes_X, diabetes_y)
print(f"Coefficients:\n {ridge_model.coef_.T}\n")

Coefficients:
 [  20.13800709 -131.24149467  383.48370376  244.83506964  -15.18674139
  -58.34413649 -174.84237091  121.9849503   328.4987567   110.8864333 ]



### Lasso

Lasso regression is also a regularization technique, but instead of penalizing using an $\ell_2$-norm, it considers an $\ell_1$-penalization. It is useful in some contexts due to its tendency to prefer solutions with fewer non-zero coefficients and even it could be utilized as a way to select features in a model.

$$
\min_\beta J(\beta) = \min_{\beta} \frac{1}{2n}  \left\lVert y - X \beta \right\rVert^2_2 + \alpha \left\lVert \beta \right\rVert_1^2
$$

where $\left\lVert \beta \right\rVert_1 = \sum_{i=0}^p \left\lvert \beta_i \right\rvert$.

In [9]:
from sklearn.linear_model import Lasso

lasso_model = Lasso(alpha=0.5)
lasso_model.fit(diabetes_X, diabetes_y)
print(f"Coefficients:\n {lasso_model.coef_.T}\n")

Coefficients:
 [  0.          -0.         471.04187427 136.50408382  -0.
  -0.         -58.31901693   0.         408.0226847    0.        ]



### Elastic-Net 

Elastic-Net is a compromise between Ridge and Lasso regression, considering both $\ell_1$ and $\ell_2$-norm regularizaion. Let's consider a ratio $\rho \in (0,1)$, then

$$
\min_\beta J(\beta) = \min_{\beta} \frac{1}{2n}  \left\lVert y - X \beta \right\rVert^2_2 + \alpha \rho \left\lVert \beta \right\rVert_1^2 + \frac{\alpha (1 - \rho)}{2} \left\lVert \beta \right\rVert_2^2
$$


In [10]:
from sklearn.linear_model import ElasticNet

elasticnet_model = ElasticNet(alpha=0.5, l1_ratio=0.4)
elasticnet_model.fit(diabetes_X, diabetes_y)
print(f"Coefficients:\n {elasticnet_model.coef_.T}\n")

Coefficients:
 [ 1.55873597  0.          6.36640961  4.61688157  1.82562593  1.36291798
 -4.0457662   4.44665465  6.10117638  3.8868802 ]

